var listReview = [
    { id: 'emvatrinh', review: 'Câu chuyện của Em Và Trịnh lấy bối cảnh một sự kiện âm nhạc tại Paris vào thập niên 1980. Trịnh Công Sơn (NSƯT Trần Lực) lúc này đã đứng tuổi có sự xao xuyến với cô gái trẻ người Nhật tên Michiko Yoshii (Nakatani Akari) – người đã hát nhạc của mình một cách đầy truyền cảm. Michiko ngỏ ý muốn ông giúp mình hoàn thành bài luận văn thạc sĩ về yếu tố phản chiến nhạc Trịnh. Ít lâu sau, "nàng thơ" đã sang Việt Nam để tìm hiểu về người dân và văn hóa nơi đây. Phim mang lối kể chuyện đan xen giữa thực tại và quá khứ, bắt đầu với sự kiện Trịnh Công Sơn lần đầu gặp nữ sinh Nhật Michiko Yoshii (Nakatani Akari đóng) cuối thập niên 1980. Theo đuổi luận văn cao học đề tài âm nhạc phản chiến, cô sang Việt Nam để tìm hiểu về cuộc đời và con người nhạc sĩ tài hoa. Từ dòng hồi tưởng của Trịnh Công Sơn, từng lớp ký ức được lần giở, làm sống dậy một thời hoa mộng bên những nàng thơ. Ở hiện tại, ông và Michiko cũng nảy sinh những rung động nhờ mối giao cảm trong âm nhạc.' },
    { id: 'nguoikhoilua', review: 'Được chuyển thể từ tiểu thuyết cùng tên của Stephen King, Người Khởi Lửa mang đến cho mình nhiều trải nghiệm như xem phim siêu anh hùng hơn là một phim kinh dị. Với một cốt truyện hết sức bình thường, phim lại ẩn chứa bên trong những màn kĩ xảo mãn nhãn thể hiện năng lực không phải dạng vừa của cô bé Charlie. Câu chuyện phim xoay quanh gia đình gồm các thành viên sở hữu khả năng đọc được tâm trí, điều khiển đồ vật gồm người chồng Andy (Zac Efron), người vợ Vicky (Sydney Lemmon) và cô con gái Charlie (Ryan Kiera Armstrong). Charlie ngoài sở hữu năng lực di truyền từ bố mẹ còn có khả năng điều khiển được lửa. Cả gia đình McGee luôn phải trốn tránh sự săn lùng từ tổ chức DSI. Trong quá khứ, Andy và Vicky là những người thử nghiệm đầu tiên Lô 6, một loại chất tăng cường năng lực con người từ DSI. Tổ chức này muốn tìm lại các dị nhân năm xưa để tiếp tục tiến hành thử nghiệm. ' },
    { id: 'satthunhantao', review: 'Sát Thủ Nhân Tạo là bộ phim hành động li kì kể về Koo Ja-yoon - một cô bé được nuôi dưỡng trong một tổ chức đáng sợ - nơi diễn ra các cuộc thí nghiệm y học được thực hiện trên chính cơ thể con người nhằm biến họ thành những cỗ máy giết người. Sau khi chạy trốn khỏi tổ chức, Ja-yoon bị mất trí nhớ và được một cặp vợ chồng già nhận nuôi. 10 năm sau, khi đã trở thành một nữ sinh trung học, Ja-yoon đăng ký tham gia một cuộc thi âm nhạc với mong muốn giúp gia đình vượt qua khó khăn tài chính. Nhưng cô không ngờ rằng, ngay từ khi hình ảnh của mình xuất hiện trên truyền hình, cuộc sống của cô bị đảo lộn hoàn toàn bởi sự truy đuổi của những kẻ lạ mặt.' },
    { id: 'haokhichienbinh', review: 'Bộ phim này được xây dựng dựa trên câu chuyện có thật về bộ tộc Seediq - những người đã thực hiện một cuộc nổi dậy đẫm máu năm 1930 chống lại quân đội Nhật Bản để bảo vệ cuộc sống của mình... Số phận của những người dân trong bộ tộc Seediq rồi sẽ ra sao? Trong phim Hào Khí Chiến Binh, họ có thoát khỏi sự tàn sát dã man của quân đội Nhật Bản? Phim Hào Khí Chiến Binh là một bản anh hùng ca, ca ngợi những tấm gương chiến đấu một cách bất khuất vì danh dự, tự do của một dân tộc. Dù dân tộc ấy rất nhỏ bé nhưng sức mạnh tinh thần là bất diệt.' },
    { id: 'nhentrongmang', review: 'Adereth là một điệp viên già đang thực hiện một nhiệm vụ cuối cùng để chuộc lại cuộc đời và sự nghiệp của mình trước khi hết thời; nhưng khi một người phụ nữ bí ẩn xuất hiện khiến sự tin tưởng với cấp trên của anh ta bắt đầu mất dần đi, Adereth nhận ra một sự thật trong thế giới của sự lừa dối.' },
    { id: 'bacsiduong', review : 'Bộ phim là câu chuyện của Đường Giai Du, một nữ bác sĩ khoa tim đã hành nghề y ở nước ngoài nhiều năm, được Phó viện trưởng Lưu Phong mời về nước đảm nhận chức vụ Chủ nhiệm Trung tâm Tim mạch của bệnh viện An Hoà Tế Sinh Bắc Kinh. Từ việc không đánh không quen với Âu Dương Chân Dư đến việc dần dần trở thành tri kỷ cùng bác sĩ gây mê Diệp Dịch Minh. Đồng thời lại dẫn dắt 5 thành viên của nhóm bệnh hiểm nghèo: Giang Bách Liệt, Long Hướng Đông, Tần Đại Trung, Chu Đạt, Liêu Tiểu Ba cùng nhau cứu chữa 28 trường hợp mắc bệnh tim hiếm gặp. Dưới sự cố gắng và phát triển không ngừng đã thúc đẩy việc nghiên cứu và phát triển thành công "trái tim nhân tạo", tạo nên lịch sử mới của trong việc nghiên cứu tim nhân tạo ở Trung Quốc. Đồng thời nhân vật cũng nhận ra những sai lầm của bản thân và tìm ra hạnh phúc của chính mình.' },
    { id: 'nguoidanong', review: 'Harper Marlowe quyết định dành kỳ nghỉ một mình ở ngôi làng nhỏ Cotson sau vụ tự tử rõ ràng của chồng cô là James. Trong hồi tưởng, nó được tiết lộ rằng Harper, chán ngấy với sự lạm dụng và thao túng tình cảm của James, có ý định ly hôn với anh ta, khiến James đe dọa cô ấy bằng cách tự tử. Sau khi James đánh cô, Harper nhốt anh ta ra khỏi căn hộ trước khi chứng kiến anh ta rơi từ ban công trên lầu xuống chết, bị hàng rào đâm một phần. <br> <br> Harper đến trang viên rộng rãi mà cô đang thuê và được chủ sở hữu Geoffrey chào đón. Sau đó, cô đi dạo trong rừng và tình cờ gặp một đường hầm đường sắt cũ, chưa được sử dụng. Một nhân vật bí ẩn xuất hiện ở cuối đường hầm và bắt đầu đuổi theo cô, nhưng cô đã trốn tránh nó. Đến một cánh đồng trống, cô dùng điện thoại chụp một bức ảnh, vô tình chụp được một người đàn ông khỏa thân đang đứng gần một tòa nhà bỏ hoang, nhìn chằm chằm vào cô. Sau đó, trong một cuộc gọi video với người bạn Riley, Harper quan sát thấy người đàn ông trong khu vườn của cô, đã theo cô từ trong rừng. Cô gọi cảnh sát, một trong số họ trông giống Geoffrey, và người đàn ông bị bắt. Sau đó, Harper đến thăm một nhà thờ, nơi hình ảnh của Người đàn ông xanh được khắc trên phông chữ, và gặp một cậu bé và một cha xứ, cả hai đều giống Geoffrey. Cậu bé gọi cô là chó cái khi cô từ chối lời mời chơi trốn tìm của anh ta, và cha xứ nói bóng gió Harper là để đổ lỗi cho cái chết của James, hỏi cô ấy đã khiêu khích anh ta như thế nào và liệu cô ấy có để anh ta xin lỗi hay không. Buồn bã, cô đến quán rượu thị trấn theo lời giới thiệu của Geoffrey. Quán rượu có dân cư thưa thớt, nhưng khách quen và nhân viên pha chế, tất cả đều là đàn ông, tất cả đều mang ngoại hình của Geoffrey. Geoffrey cũng ở đó, cũng như cảnh sát của anh ta trông giống nhau. Viên cảnh sát thông báo cho Harper rằng người đàn ông đã được thả ra vì họ không có cơ sở pháp lý để giam giữ anh ta, trước sự hoài nghi của cô. <br> <br> '+
    'Cô ấy liên lạc với Riley về những diễn biến trong ngày và cô ấy đồng ý đến vào buổi sáng để Harper có thể tiếp tục thời gian rời đi. Khi Harper cố gắng gửi cho Riley địa chỉ, dịch vụ điện thoại của cô liên tục bị gián đoạn. Cô nhìn thấy cảnh sát trong sân của mình, nhưng khi đèn nhấp nháy, anh ta thay đổi thành một trong những khách quen của quán rượu, người sau đó đuổi theo cô trong nhà. Harper tự vệ bằng một con dao trước khi một cửa sổ bị vỡ trong nhà bếp. Geoffrey đến và thấy rằng cửa sổ bị vỡ là do một con quạ, sau đó anh ta nhận ra bằng cách bẻ cổ nó. Khi Geoffrey đi vào sân để xua đuổi bất kỳ kẻ xâm nhập nào, anh ta được thay thế bằng người đàn ông khỏa thân, người lại đuổi theo Harper. Khi anh ta cố gắng tiếp cận cô ấy qua khe thư, Harper đâm anh ta qua cánh tay. Anh ta cố gắng kéo cánh tay của mình tự do, con dao bị mắc kẹt xé toạc cánh tay anh ta làm đôi trong một chấn thương giống như cái mà James nhận được trong cú ngã của mình. Cả cậu bé và cha xứ đều xuất hiện trong nhà, mỗi người trong số họ bây giờ đều bị thương như nhau. Cha xứ cố gắng cưỡng hiếp Harper, nhưng cô đã đâm vào bụng anh ta và rời khỏi nhà.'},
    { id: 'nguoikenhiemnamsan', review: 'Bộ phim mang đề tài chính trị hình sự của Hàn Quốc vào những năm 1970. Chủ đề chính xoay quanh cuộc ám sát tổn thống của một nhân viên làm việc dưới cơ của vị tổn thống. Liệu có gì uẩn khúc quanh vụ án này, những người liên quan thì sao? Hãy cùng đợi xem phim để biết rõ tường tận là tại sao nha! “Tại sao hắn bóp cò?”. Câu hỏi đầy tính đe dọa và ẩn ý viết trên poster đậm màu đen tối như báo hiệu trước một tác phẩm nặng đô. Sau Mount Baekdu nặng tính hành động, Lee Byung Hun chào sân 2020 với một tựa phim chính trị sặc mùi âm mưu. The Man Standing Next được sản xuất dựa trên cuốn sách cùng tên khám phá những uẩn khuất đằng sau một vụ ám sát chấn động. Ngày 26/10/1979, giám đốc Cục Trí Tuệ Trung Tâm Hàn Quốc Kim Kyu Pyung (Lee Byung Hun) đã nổ súng ám sát tổng thống Park (Lee Sung Min). Động cơ nào khiến một nhân viên chính phủ sát hại chính tống thống của mình và những kẻ nào còn liên đới? Câu chuyện chính trị đen tối và kịch tính với diễn xuất tuyệt vời của Lee Byung Hun được kì vọng sẽ tạo một “bom tấn” sớm cho thập kỉ mới của điện ảnh Hàn.' },
    { id: 'contautitanic', review: 'Titanic là một bộ phim điện ảnh lãng mạn thảm họa sử thi của Mỹ phát hành năm 1997, do James Cameron làm đạo diễn, viết kịch bản, đồng sản xuất, đồng biên tập và hỗ trợ tài chính một phần. Phim lấy ý tưởng dựa trên vụ đắm tàu RMS Titanic nổi tiếng trong lịch sử vào năm 1912, với sự tham gia của các diễn viên chính Leonardo DiCaprio và Kate Winslet trong vai hai con người đến từ hai tầng lớp khác nhau trong xã hội, họ đem lòng yêu nhau trên chuyến ra khơi đầu tiên của con tàu xấu số. <br> <br> Cảm hứng của Cameron cho bộ phim đến từ sự say mê của ông với những xác tàu đắm (chính ông đã khẳng định như vậy); ông muốn truyền tải một thông điệp tình cảm từ thảm họa và thấy rằng một câu chuyện tình lãng mạn kết thúc bằng sự ra đi của một trong hai người sẽ giúp ông làm được điều này. Quá trình sản xuất phim bắt đầu từ năm 1995, khi Cameron bắt đầu quay cảnh xác chiếc tàu Titanic nằm dưới đáy đại dương. Các phân cảnh hiện tại được quay trên tàu Akademik Mstislav Keldysh, và đây cũng là nơi Cameron sử dụng làm chỗ ở và căn cứ cho đoàn làm phim khi quay cảnh xác tàu. Một con tàu Titanic mới cũng đã được dựng lại ở Playas de Rosarito thuộc Baja California; các mô hình thu nhỏ và công nghệ mô phỏng hình ảnh trên máy tính được sử dụng để tái tạo cảnh tàu chìm. Kinh phí thực hiện bộ phim do Paramount Pictures và 20th Century Fox cung cấp, vào thời điểm đó, đây là bộ phim có kinh phí cao nhất trong lịch sử, với tổng mức đầu tư ước tính khoảng 200 triệu đô la Mỹ.' },
    { id: 'kieu', review: 'Kiều là một bộ phim điện ảnh cổ trang của Việt Nam do Mai Thu Huyền sản xuất và đạo diễn, được lấy cảm hứng từ tác phẩm Truyện Kiều của Nguyễn Du. Là dự án phim đầu tiên của Mai Thu Huyền trong vai trò đạo diễn, phim có sự tham gia diễn xuất của Trình Thị Mỹ Duyên, Cao Thái Hà, Lê Anh Huy, NSND Lê Khanh, Phương Thanh, Hiếu Hiền, Long Đẹp Trai và Lê Thu An, chủ yếu xoay quanh câu chuyện tình cảm tay ba giữa các nhân vật Thúy Kiều, Thúc Sinh và Hoạn Thư.<br> <br> Phim Kiều tập trung xoay quanh khoảng thời gian gia đình Vương viên ngoại gặp án oanh, con gái cả Thúy Kiều phải bán mình chuộc cha và em trai. Sống cuộc đời đau khổ, không có ánh sáng ở lầu xanh, Kiều vô tình gặp Thúc Sinh, một khách làng chơi giàu có đem lòng yêu thương, chuộc nàng ra khỏi chốn phong trần. <br> <br> Tuy nhiên, Thúy Kiều nào biết Thúc Sinh ở nhà đã có vợ là Hoạn Thư. Ghen tức chuyện chồng có tình nhân khác, Hoạn Thư dùng lời lẽ đánh ghen, lên kế hoạch hãm hại Kiều. Nàng được Thúc Sinh cứu khỏi thảo khấu, trốn về vùng thâm sơn để sống. ' },
    { id: 'chimuoiba', review: 'Chị Mười Ba 3 Ngày Sinh Tử thuộc thể loại hành động, khai thác chủ đề mới mẻ với nội dung kể về cuộc chiến ngầm của giới giang hồ. Bộ phim là cuộc hành trình khó khăn và đầy thử thách khi phải vượt qua 3 ngày sinh tử để bảo vệ những người anh em của chị Mười Ba.<br> <br> Khởi đầu phim với sự kiện Kẽm Gai ra tù, Chị Mười Ba – thủ lĩnh nhóm An Cư Nghĩa Đoàn, cùng các anh em thân thiết quyết định dọn về Đà Lạt mở garage sửa chữa xe, bắt đầu làm lại cuộc sống mới nhẹ nhàng hơn, tránh khỏi những xô bồ, thị phi. Tuy nhiên, cả nhóm tiếp tục gặp rắc rối và rơi vào vòng nguy hiểm khi Đức Mát – đàn em của ông trùm Thắng Khùng bị sát hại, nghi vấn lập tức đổ dồn vào Kẽm Gai. <br> <br> Chị Mười Ba chỉ có 3 ngày để tìm ra được chứng cứ ngoại phạm và minh oan cho Kẽm Gai. ' },
    { id: 'hoaraemyeuanhratnhieu', review: 'Phim ngôn tình Hóa Ra Em Rất Yêu Anh kể về mối tình của cô phát thanh viên tương lai Tang Vô Yên (Vạn Bằng) và anh chàng mù điển trai Tô Niệm Khâm (Lâm Ngạn Tuấn). Cuộc tình dần dần đi đến đoạn kết ngọt ngào khi Vô Yên nhận ra crush bí ẩn lâu năm của mình - người viết lời có bút danh Nhất Kim chính là Niệm Khâm.<br> <br> Sau khi bị phản bội bởi Ngụy Hạo và Hứa Thiến, Tang Vô Yên (Vạn Bằng) – cô sinh viên năm cuối ngành phát thanh tình cờ gặp chàng trai khiếm thị Tô Niệm Khâm (Lâm Ngạn Tuấn) trong công viên, từ đó mở ra duyên phận của hai người. <br> <br> Trải qua nhiều biến cố cuộc đời, chàng thiếu gia tài hoa Tô Niệm Khâm trở nên trầm lặng, lạnh lùng. Tang Vô Yên cố chấp bước vào cuộc sống của Tô Niệm Khâm, sưởi ấm và làm tan chảy băng giá trong lòng anh. Tuy nhiên chuyện tình cảm của cả hai gặp nhiều thử thách, Tang Vô Yên và Tô Niệm Khâm đành buông tay nhau.' },
    { id: 'thuyhautu', review: '"Ma nước" còn được gọi là " Khỉ Nước" . Tương truyền rằng những người chết đuối, tự tử dưới nước sẽ trở thành ma nước. Sau đó kiên nhẫn đợi dưới nước, dụ hoặc ép người rơi xuống nước chết, làm ma thay thế cho chính mình. Hàng ngàn năm nay, ma nước đã dùng phương pháp này để đầu thai và thoát khỏi sự thống khổ của địa ngục. Vào thời Trung Hoa Dân Quốc, có một nơi gọi là "Làng Thiên Thủy" có núi bao quanh, lão thái gia sinh ra ở đó, dưới sự lãnh đạo của trưởng làng, dân làng có một cuộc sống ấm no đầy đủ. Cho đến một đêm, lão thái gia ngồi thuyền trở về, và những điều kỳ lạ bắt đầu xảy ra trong làng ...' },
    { id: 'thuamecondi', review: 'Sau nhiều năm du học ở Mỹ, Văn cùng người yêu là Ian về lại Việt Nam thăm gia đình nhân dịp di dời mộ phần cha mình. Đại gia đình Văn gồm có bà nội nay đã lú lẫn, bà mẹ đã góa phụ, chú thím cùng hai người con, và cô út. Vì là cháu đích tôn, Văn chịu nhiều áp lực từ gia đình để tìm vợ và có con để nối dõi. Văn và Ian phải lén lút khi muốn âu yếm với nhau để khỏi bị gia đình phát hiện. Văn hứa khi tìm được lúc thích hợp sẽ nói chuyện hai người cho gia đình. <br> <br> Bà nội, do bị lú lẫn, nhầm lẫn Ian với Văn. Bà chứng kiến cảnh hai người ôm hôn nhau và hỏi Ian về mối quan hệ hai người và Ian kể hết cho bà nội nghe. Vào ngày đám giỗ cha, người chú Văn hỏi anh trước dòng họ khi nào lấy vợ và anh trả lời rằng sẽ lấy vợ "sớm". Nghe được, bà nội nổi giận và cho rằng anh đã phụ tình người yêu (Ian). Được mẹ hỏi về ý định tương lai của mình, Văn cho biết anh sẽ lập gia đình tại Mỹ và bảo lãnh mẹ qua đó luôn. Ian chán nản với việc phải giấu giếm mối quan hệ và đòi Văn phải công khai. Văn bối rối vì vừa biết được mẹ mình bệnh nặng - anh thổ lộ với Ian về điều khó xử nhưng mẹ anh lại nghe được, do đó biết đến sự tình. <br> <br> Trong lúc đi bộ trên đường, Ian bị người em họ của Văn cùng bạn bè quấy rối, lấy điện thoại. Hai bên xô xát nhưng rốt cuộc người em họ bị bà nội đánh đuổi. Về nhà, các xích mích trong đại gia đình bị trầm trọng hơn sau khi Văn đánh người em họ và rốt cuộc gia đình bị chia rẽ. <br> <br> Bộ phim kết thúc khi mẹ Văn đi tiễn anh và Ian về lại Mỹ. Văn hứa sẽ bảo lãnh mẹ và mẹ anh lái xe về. Tại sân bay, Ian tiết lộ rằng mẹ Văn đã chúc hai người hạnh phúc bên nhau.' },
    { id: 'thienngabongdem', review: 'Bộ phim kể về vụ ly hôn nghìn tỷ chấn động cả nước, phía sau sự kiện ấy là một người phụ nữ đã dành 13 năm để lên kế hoạch trả thù một cách tàn bạo, chấn động giới thượng lưu giàu có bậc nhất Hàn Quốc - Lee Rael (Seo Ye-ji). Mục tiêu chính của cô là Kang Yoon-gyeom (Park Byung-eun), chủ tịch tập đoàn LY và là chồng của Han So-ra (Yoo Sun). <br><br> Đồng hành cùng cô là một luật sư nhân quyền, thành viên Quốc Hội trẻ tuổi nhất Seo Eun Pyung (Lee Sang-yeob), và anh từng là một đứa trẻ mồ côi được gia đình Rael nuôi dưỡng. Sau này anh phải lòng Rael và sẵn sàng hi sinh mọi thứ cho cô. Vì chứng kiến gia đình vô tội của người bạn thời thơ ấu và tình yêu của mình bị chà đạp, Eun Pyung quyết tâm trở thành người nắm quyền lực tuyệt đối để bảo vệ người ấy.' },
    { id: 'thuamecondi', review: '' },
    { id: 'tiectrangmau', review: 'Phim xoay quanh một nhóm bạn thân thiết ở độ tuổi tứ tuần cùng hội tụ vào buổi tiệc tân gia tại căn penthouse sang trọng của cặp vợ chồng giàu có Nguyệt Ánh (Hồng Ánh) - Ngọc Quang (Hứa Vĩ Văn). Tại đây, cả nhóm đã tổ chức trò chơi công khai toàn bộ nội dung tin nhắn, cuộc gọi, email,... nhận được trong thời gian trò chơi diễn ra. Và từ đây, các bí mật, góc tối của mỗi nhân vật dần được phơi bày và đưa diễn biến phim lên cao trào. Bắt đầu từ những mâu thuẫn nhỏ nhặt thường ngày cho đến những tình tiết kịch tính, sự thật kinh hoàng khiến các mối quan hệ tan vỡ. <br> <br> Phim dẫn dắt người xem vào câu chuyện một cách tự nhiên qua các tình tiết đời thường và các tuyến nhân vật quen thuộc có thể bắt gặp ở bất cứ đâu trong xã hội. Tuy nhiên càng về sau người xem sẽ càng bị hấp dẫn bởi các bí mật, những dối trá, lừa gạt và phản bội không thể đoán trước từ mỗi nhân vật tưởng chừng như rất bình thường.' },
    { id: 'matranhoisinh', review: 'Ma Trận Hồi Sinh (The Matrix 4: Resurrections): 18 năm sau bộ phim thứ ba và cuối cùng, phần thứ 4 của Ma Trận trở lại với rất nhiều điều quen thuộc bao gồm: dàn diễn viên chính Keanu Reeves và Carrie-Anne Moss, những đoạn mã code màu xanh lá đẹp mắt, phần hành động ấn tượng, các viên thuốc màu xanh đỏ nổi tiếng, những cái chạm nhẹ gợn sóng trên mặt gương hay cả tốc độ bay của viên đạn… <br> Ma Trận Hồi Sinh khơi gợi lại rất nhiều tình huống từ 3 phần đầu tiên với những cuộc hội ngộ, đi kèm những đoạn hội thoại kéo dài nhưng dường như không giải quyết thêm được vấn đề gì mới. Cốt truyện của bộ phim cũng lặp lại cấu trúc từ phần đầu tiên nhưng không đem lại cảm giác tinh tế bằng. Các ý tưởng sáng tạo mới thì khá đơn giản và dễ đoán, thậm chí có phần hơi sến, khiến bộ phim hoàn toàn ở một mức thấp hơn rất nhiều so với các phần trước đó. <br>Ma Trận Hồi Sinh (The Matrix 4: Resurrections) là phần thứ 4 của loạt phim khoa học viễn tưởng ra mắt vào năm 1999, xoay quanh nhân vật Thomas A. Anderson / The One / Neo, một lập trình viên và cũng là một hacker máy tính, vô tình gặp được cô nàng nổi loạn Trinity (Carrie-Anne Moss) và nhân vật bí ẩn của Morpheus (Laurence Fishburne). Cuộc gặp gỡ này đã giúp Neo hiểu thêm về thuật ngữ “Ma Trận” và phân cảnh lựa chọn nổi tiếng: viên thuốc màu xanh như sự hài lòng về cuộc sống hiện tại và viên thuốc màu đỏ đại diện cho sự tồn tại thật sự, cùng tự do về ý chí.' },
    { id: 'thuyquairunggomun',review: 'Thanh Linh, một nữ bác sĩ pháp y của Trung Hoa Dân Quốc quay trở lại thị trấn Thượng Thuỷ nơi mình từng sinh sống để tìm kiếm người em trai đã mất tích. Nhưng cũng ở đây, cô vô tình phát hiện được bí mật về thân phận của mình. Cô nỗ lực xoá bỏ hủ tục mê tín phong kiến ​​bằng nền văn minh khoa học, dùng sự thật thức tỉnh người dân thị trấn để chống lại thế lực xấu xa.' },
    { id: 'yeutinh', review: 'Yêu tinh (Poltergeist) là một bộ phim kinh dị siêu nhiên Mỹ 2015 của đạo diễn Gil Kenan do David Lindsay-Abaire viết và sản xuất bởi Sam Raimi.Đây là phiên bản làm lại của phim cùng tên 1982, với sự tham gia của Sam Rockwell, Rosemarie DeWitt, Jared Harris và Jane Adams. Phim được phát hành vào ngày 22 tháng 5 năm 2015 bởi 20th Century Fox, nhận được nhiều đánh giá tích cực từ chuyên môn và có doanh thu trên $95 triệu.' },
    { id: 'thegioikhunglong', review: 'Thế Giới Khủng Long: Lãnh Địa kể về bốn năm sau kết thúc Jurassic World: Fallen Kingdom, những con khủng long đã thoát khỏi nơi giam cầm và tiến vào thế giới loài người. Giờ đây, chúng xuất hiện ở khắp mọi nơi. Sinh vật to lớn ấy không còn chỉ ở trên đảo như trước nữa mà gần ngay trước mắt, thậm chí còn có thể chạm tới. Owen Grady may mắn gặp lại cô khủng long mà anh và khán giả vô cùng yêu mến - Blue. Tuy nhiên, Blue không đi một mình mà còn đem theo một chú khủng long con khác. Điều này khiến Owen càng quyết tâm bảo vệ mẹ con cô được sinh sống an toàn. Thế nhưng, hai giống loài quá khác biệt. Liệu có thể tồn tại một kỷ nguyên mà khủng long và con người sống chung một cách hòa bình?'}
];
var idphim = localStorage.getItem('id-phim');
for (let i = 0; i < listReview.length; i++) {
    if (idphim == listReview[i].id) {
        document.getElementById('review-phim').innerHTML = listReview[i].review;
        break;
    }
}
var flag = true;
function Overflow() {
    if (flag) {
        document.getElementById('xemthem').innerHTML = 'Rút gọn';
        document.getElementById('review-phim').style.height = 'fit-content';
        document.getElementById('review-phim').style.transition = 'all 1s';
        flag = !flag;
    } else {
        document.getElementById('review-phim').style.height = '65px';
        document.getElementById('review-phim').style.transition = 'all 1s';
        document.getElementById('xemthem').innerHTML = 'Xem thêm';
        flag = !flag;
    }
    
}